/*
 * IDENTIFICATION:
 * stub generated by bootstrap_cmds-129
 * OPTIONS:
 */

/* Module mach_exc */

#define    __MIG_check__Request__mach_exc_subsystem__ 1

#include "mach_excServer.h"

#ifndef    mig_internal
#define    mig_internal    static __inline__
#endif    /* mig_internal */

#ifndef    mig_external
#define mig_external
#endif    /* mig_external */

#if    !defined(__MigTypeCheck) && defined(TypeCheck)
#define    __MigTypeCheck        TypeCheck    /* Legacy setting */
#endif    /* !defined(__MigTypeCheck) */

#if    !defined(__MigKernelSpecificCode) && defined(_MIG_KERNEL_SPECIFIC_CODE_)
#define    __MigKernelSpecificCode    _MIG_KERNEL_SPECIFIC_CODE_    /* Legacy setting */
#endif    /* !defined(__MigKernelSpecificCode) */

#ifndef    LimitCheck
#define    LimitCheck 0
#endif    /* LimitCheck */

#ifndef    min
#define    min(a,b)  ( ((a) < (b))? (a): (b) )
#endif    /* min */

#if !defined(_WALIGN_)
#define _WALIGN_(x) (((x) + 3) & ~3)
#endif /* !defined(_WALIGN_) */

#if !defined(_WALIGNSZ_)
#define _WALIGNSZ_(x) _WALIGN_(sizeof(x))
#endif /* !defined(_WALIGNSZ_) */

#ifndef    UseStaticTemplates
#define    UseStaticTemplates    0
#endif    /* UseStaticTemplates */

#ifndef MIG_SERVER_ROUTINE
#define MIG_SERVER_ROUTINE
#endif

#ifndef    __DeclareRcvRpc
#define    __DeclareRcvRpc(_NUM_, _NAME_)
#endif    /* __DeclareRcvRpc */

#ifndef    __BeforeRcvRpc
#define    __BeforeRcvRpc(_NUM_, _NAME_)
#endif    /* __BeforeRcvRpc */

#ifndef    __AfterRcvRpc
#define    __AfterRcvRpc(_NUM_, _NAME_)
#endif    /* __AfterRcvRpc */

#ifndef    __DeclareRcvSimple
#define    __DeclareRcvSimple(_NUM_, _NAME_)
#endif    /* __DeclareRcvSimple */

#ifndef    __BeforeRcvSimple
#define    __BeforeRcvSimple(_NUM_, _NAME_)
#endif    /* __BeforeRcvSimple */

#ifndef    __AfterRcvSimple
#define    __AfterRcvSimple(_NUM_, _NAME_)
#endif    /* __AfterRcvSimple */

#define novalue void

#define msgh_request_port    msgh_local_port
#define MACH_MSGH_BITS_REQUEST(bits)    MACH_MSGH_BITS_LOCAL(bits)
#define msgh_reply_port        msgh_remote_port
#define MACH_MSGH_BITS_REPLY(bits)    MACH_MSGH_BITS_REMOTE(bits)

#define MIG_RETURN_ERROR(X, code)    {\
                ((mig_reply_error_t *)X)->RetCode = code;\
                ((mig_reply_error_t *)X)->NDR = NDR_record;\
                return;\
                }

/* Forward Declarations */

mig_internal novalue _Xmach_exception_raise_state_identity
    (mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_external boolean_t mach_exc_server
    (mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{
    OutHeadP->msgh_bits = MACH_MSGH_BITS(MACH_MSGH_BITS_REPLY(InHeadP->msgh_bits), 0);
    OutHeadP->msgh_remote_port = InHeadP->msgh_reply_port;
    /* Minimal size: routine() will update it if different */
    OutHeadP->msgh_size = (mach_msg_size_t)sizeof(mig_reply_error_t);
    OutHeadP->msgh_local_port = MACH_PORT_NULL;
    OutHeadP->msgh_id = InHeadP->msgh_id + 100;
    OutHeadP->msgh_reserved = 0;
    
//    if ((InHeadP->msgh_id > 2409) || (InHeadP->msgh_id < 2405) ||
//        ((routine = catch_mach_exc_subsystem.routine[InHeadP->msgh_id - 2405].stub_routine) == 0)) {
    if (InHeadP->msgh_id != 2407) {
        ((mig_reply_error_t *)OutHeadP)->NDR = NDR_record;
        ((mig_reply_error_t *)OutHeadP)->RetCode = MIG_BAD_ID;
        return FALSE;
    }
    //(*routine) (InHeadP, OutHeadP);
    _Xmach_exception_raise_state_identity(InHeadP, OutHeadP);
    return TRUE;
}
mig_internal novalue _Xmach_exception_raise_state_identity
    (mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{
#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
    typedef struct {
        mach_msg_header_t Head;
        /* start of the kernel processed data */
        mach_msg_body_t msgh_body;
        mach_msg_port_descriptor_t thread;
        mach_msg_port_descriptor_t task;
        /* end of the kernel processed data */
        NDR_record_t NDR;
        exception_type_t exception;
        mach_msg_type_number_t codeCnt;
        int64_t code[2];
        int flavor;
        mach_msg_type_number_t old_stateCnt;
        natural_t old_state[1296];
        mach_msg_trailer_t trailer;
    } Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
    typedef __Request__mach_exception_raise_state_identity_t __Request;
    typedef __Reply__mach_exception_raise_state_identity_t Reply __attribute__((unused));

    /*
     * typedef struct {
     *     mach_msg_header_t Head;
     *     NDR_record_t NDR;
     *     kern_return_t RetCode;
     * } mig_reply_error_t;
     */

    Request *In0P = (Request *) InHeadP;
    Request *In1P = In0P;
    Reply *OutP = (Reply *) OutHeadP;
#ifdef    __MIG_check__Request__mach_exception_raise_state_identity_t__defined
    kern_return_t check_result;
#endif    /* __MIG_check__Request__mach_exception_raise_state_identity_t__defined */

    //__DeclareRcvRpc(2407, "mach_exception_raise_state_identity")
    //__BeforeRcvRpc(2407, "mach_exception_raise_state_identity")

#if    defined(__MIG_check__Request__mach_exception_raise_state_identity_t__defined)
    check_result = __MIG_check__Request__mach_exception_raise_state_identity_t((__Request *)In0P, (__Request **)&In1P);
    if (check_result != MACH_MSG_SUCCESS)
        { MIG_RETURN_ERROR(OutP, check_result); }
#endif    /* defined(__MIG_check__Request__mach_exception_raise_state_identity_t__defined) */

    OutP->new_stateCnt = 1296;

    OutP->RetCode = catch_mach_exception_raise_state_identity(In0P->Head.msgh_request_port, In0P->thread.name, In0P->task.name, In0P->exception, In0P->code, In0P->codeCnt, &In1P->flavor, In1P->old_state, In1P->old_stateCnt, OutP->new_state, &OutP->new_stateCnt);
    if (OutP->RetCode != KERN_SUCCESS) {
        MIG_RETURN_ERROR(OutP, OutP->RetCode);
    }

    OutP->NDR = NDR_record;


    OutP->flavor = In1P->flavor;
    OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply) - 5184) + (((4 * OutP->new_stateCnt)));

    //__AfterRcvRpc(2407, "mach_exception_raise_state_identity")
}
