name: Build LCTaskForPIDTweak

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        xcodebuild -scheme LCTaskForPIDTweak \
                   -project LCTaskForPIDTweak.xcodeproj \
                   -configuration Release \
                   -sdk iphoneos \
                   -derivedDataPath build \
                   CODE_SIGNING_ALLOWED=NO \
                   CODE_SIGNING_REQUIRED=NO \
                   CODE_SIGN_IDENTITY="" \
                   AD_HOC_CODE_SIGNING_ALLOWED=YES

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: LCTaskForPIDTweak.dylib
        path: build/Build/Products/Release-iphoneos/LCTaskForPIDTweak.dylib

    - name: Nightly Release
      uses: andelf/nightly-release@5834076edc55cc05975561c9722043f072ac5c26
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        body: |
            **Commit:** [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
            **Message:** ${{ github.event.head_commit.message }}
            
            This is a nightly release [created automatically with GitHub Actions workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}).
        files: |
            build/Build/Products/Release-iphoneos/LCTaskForPIDTweak.dylib
